### PR TITLE
Fix gpu #6640

### PR DESCRIPTION
**Pull request by pallavi-pannu-oc**

### CODE REVIEW

**Comment by mak-454** [comment]
@pallavi-pannu-oc This is already supported right.
Please see this function -     def update_distribution(self, opt=DISTRIBUTION_OPTS[0], nworkers=0):

Can you check why override is being sent True, since default value is "manual"

**This change is not required.** As user may not know the meaning of flag **override**

Please check.

@songole please do not merge this PR.

**Comment by pallavi-pannu-oc** [comment]
@mak-454 

https://github.com/oneconvergence/dkube/blob/aa0516828f758546fcdf153d25a5cf2a72c53d2e/dkube/sdk/internal/dkube_api/models/ds_job_model.py#L63

here gpu_override=True.

Yes , we don't need the update_flag function as we are already having update_distribution but i think we need to set 
gpus_override = False

self.notebook_def = DSJobModel(executor=self.executor_def, datums=self.input_datums,
                                       rdma=False, hyperparams=self.hyperparameters, hptuning=self.hptuning)
                                       rdma=False, hyperparams=self.hyperparameters, hptuning=self.hptuning,**gpus_override=False)**

**Comment by songole** [comment]
@mak-454 Are there any concerns in merging this?

**Comment by mak-454** [comment]
@pallavi-pannu-oc can u remove update_flag function ?

**Comment by songole** [comment]
@riteshkarvaloc

**Comment by mak-454** [comment]
new implementation here - https://github.com/oneconvergence/dkube/pull/53
Closing this PR as gpus_override flag is internal and cannot be understood by user.
@pallavi-pannu-oc @riteshkarvaloc @songole check the PR #53

**Pull request closed without merging**
